### ISSUE TITLE
NullReferenceException in FormsWebViewRenderer.DidReceiveScriptMessage

### ISSUE THREAD

**Issue by madcreep** [SKLn-Rad/Xam.Plugin.Webview#25] opened 2017-05-31 08:34 UTC
Sometimes the method 'FormsWebViewRenderer.DidReceiveScriptMessage (WebKit.WKUserContentController userContentController, WebKit.WKScriptMessage message)' raises a NullReferenceException.

**Comment by SKLn-Rad** [comment] 2017-05-31 08:52
Same as my other comment! Ideally this could only happen due to two conditions.
1) Either the element is null which shouldn't be the case as you need it to inject in the first place.
2) The message returned is null, in which case message.Body would throw this exception.

Would you be able to get a sample to me as to how you reproduced this issue!

Thanks,
Ryan

**Comment by madcreep** [comment] 2017-05-31 08:57
You're absolutely right: either message or message.Body is null.
The thing is, as in the previous comment, is it possible to avoid the exception in this case? Like this: 

`public void DidReceiveScriptMessage(WKUserContentController userContentController, WKScriptMessage message)
        {
            Element.InvokeEvent(WebViewEventType.JavascriptCallback, new JavascriptResponseDelegate(Element, message?.Body?.ToString()));
        }`

Thanks,
Sergey

**Comment by Lachlangg** [comment] 2017-07-05 04:21
I've been having the same issue and can reproduce reliably. It happen for me if I navigate away from my page that has a webview while a lengthy JS operation is in progress. When the JS finishes and tries to run the call back it hits the exception.

I think it can't invoke the event because the C# Action no longer exists.

As a Workaround I've added a line to OnDisappearing() to navigate away from my page so it can't be called. I navigate to our company logo incase something strange happens and it ends up visible but you can use anywebsite you know won't run a call back.

e.g.
internetContent.Source = "http://google.com";

**Comment by SKLn-Rad** [comment] 2017-07-12 14:36
Hey guys! Sorry for the incredibly slow response. You would not believe the couple of months I have been having.

Anyway, I have found the root cause and am about to release a patch tonight for it! Thanks for the detailed reproduction steps Lachlangg, they really helped.

Update your projects in the next couple of hours! I am just going over a few of the other bugs :)

- Ryan

**Comment by SKLn-Rad** [comment] 2017-07-12 15:24
https://www.nuget.org/packages/Xam.Plugin.WebView/1.6.0
Let me know if this fixes it for you so I can close this :)

**Comment by SKLn-Rad** [comment] 2017-07-27 07:28
Closing as no reply and seems okay my end.

**Closed by SKLn-Rad** 2017-07-27 07:28 UTC
Labels: bug
